import { Menu, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { cn } from "../../lib/cn";

export function Brand() { return <Link to="/" className="motion-nav-link rounded-lg font-display text-3xl tracking-tight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">CrossBorder<sup className="ml-0.5 align-super font-sans text-[.32em]">®</sup></Link>; }
export function AppShell({ children, operations = false }: { children: ReactNode; operations?: boolean }) {
  const [open, setOpen] = useState(false);
  const { pathname } = useLocation();
  const links = operations ? [["Receive package", "/warehouse/receive"], ["Rates", "/admin/rates"]] : [["New quotation", "/quote"], ["Rates", "/rates"], ["Track order", "/#tracking"]];
  return <div className="min-h-screen bg-canvas text-ink"><header className="motion-shell-header sticky top-0 z-40 border-b border-black/[.06] bg-canvas/90 backdrop-blur-xl"><nav aria-label="Primary navigation" className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between px-5 sm:px-6 lg:px-8"><Brand /><div className="hidden items-center gap-2 md:flex">{links.map(([label, path]) => <NavLink key={path} to={path} className={({ isActive }) => cn("motion-nav-link rounded-full px-4 py-2.5 text-sm font-medium text-muted hover:bg-white hover:text-ink", isActive && "bg-white text-ink shadow-soft")}>{label}</NavLink>)}{!operations && <Link to="/warehouse/receive" className="motion-nav-link ml-2 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white">Operations</Link>}</div><button type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)} className="motion-icon-button grid h-11 w-11 place-items-center rounded-full border border-black/10 bg-white md:hidden">{open ? <X /> : <Menu />}</button></nav>{open && <div className="motion-mobile-menu border-t border-black/[.06] bg-white p-4 md:hidden">{links.map(([label, path]) => <Link key={path} to={path} onClick={() => setOpen(false)} className="motion-nav-link block rounded-xl px-4 py-3 text-sm font-semibold text-muted hover:bg-brand-soft">{label}</Link>)}</div>}</header><main key={pathname} className="motion-page-enter">{children}</main><footer className="motion-footer mt-20 border-t border-black/[.06]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm text-muted sm:flex-row sm:items-center sm:justify-between"><Brand /><p>Transparent assisted shopping and logistics.</p><Link to={operations ? "/" : "/warehouse/receive"} className="motion-nav-link font-semibold text-ink">{operations ? "Customer experience" : "Warehouse operations"}</Link></div></footer></div>;
}
export function PageHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="motion-page-header mb-10 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">{eyebrow}</p><h1 className="mt-3 font-display text-5xl leading-[.98] tracking-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">{description}</p></header>; }
export function PageContainer({ children, narrow = false }: { children: ReactNode; narrow?: boolean }) { return <div className={cn("mx-auto w-full px-5 py-12 sm:px-6 lg:px-8 lg:py-16", narrow ? "max-w-4xl" : "max-w-7xl")}>{children}</div>; }
