import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowRight, Link2, PackageSearch, Sparkles } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell, PageContainer, PageHeader } from "../app/layouts/AppShell";
import { Button } from "../components/ui/Button";
import { ErrorPanel } from "../components/ui/Feedback";
import { Field } from "../components/ui/Field";
import { Money } from "../components/ui/Money";
import { frontendApi } from "../features/api";
import { getDemoIdentity, rememberQuotation } from "../lib/storage";

const SAMPLE_URL = "https://shop.example/item/keyboard?name=Wireless%20Keyboard&price=50&currency=USD";
const stages = ["Reading product information", "Checking item eligibility", "Retrieving exchange rates", "Calculating your quotation"];
export function validateQuotationInput(url: string, quantity: number) { if (!url.trim()) return { url: "Enter a supported product URL." }; try { const parsed = new URL(url); if (parsed.protocol !== "https:") return { url: "Use a secure HTTPS product URL." }; } catch { return { url: "Enter a valid product URL." }; } if (!Number.isInteger(quantity) || quantity < 1 || quantity > 100) return { quantity: "Quantity must be a whole number from 1 to 100." }; return {}; }

export function NewQuotationPage() {
  const navigate = useNavigate(); const [productUrl, setProductUrl] = useState(""); const [quantity, setQuantity] = useState(1); const [errors, setErrors] = useState<{ url?: string; quantity?: string }>({}); const [stage, setStage] = useState(0);
  const rates = useQuery({ queryKey: ["rates"], queryFn: frontendApi.getRates });
  const mutation = useMutation({ mutationFn: frontendApi.createQuotation, onSuccess: (quotation) => { rememberQuotation(quotation.id); navigate(`/quote/${quotation.id}`); } });
  useEffect(() => { if (!mutation.isPending) { setStage(0); return; } const timer = window.setInterval(() => setStage((value) => Math.min(value + 1, stages.length - 1)), 850); return () => window.clearInterval(timer); }, [mutation.isPending]);
  const submit = (event: FormEvent) => { event.preventDefault(); const next = validateQuotationInput(productUrl, quantity); setErrors(next); if (!Object.keys(next).length) mutation.mutate({ customerId: getDemoIdentity(), productUrl: productUrl.trim(), quantity }); };
  return <AppShell><PageContainer narrow><PageHeader eyebrow="Quotation · Step 1 of 4" title="Start with the product." description="Paste a product link from a source supported by this demo. We will extract its details and return a transparent quotation in VND." />
    <div className="grid gap-6 lg:grid-cols-[1fr_280px]"><form noValidate onSubmit={submit} className="rounded-[2rem] border border-black/[.07] bg-white p-6 shadow-card sm:p-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-soft text-brand"><Link2 /></span><div><h2 className="font-semibold">Product details</h2><p className="text-sm text-muted">Only the link and quantity are needed.</p></div></div><div className="mt-7 grid gap-6"><Field id="product-url" label="Product URL" type="url" required value={productUrl} onChange={(e) => { setProductUrl(e.target.value); setErrors({ ...errors, url: undefined }); }} error={errors.url} placeholder="https://shop.example/item/..." hint="Demo sources: shop.example and example.com. Other configured sources may be available in hybrid mode." /><Field id="quantity" label="Quantity" type="number" required min={1} max={100} step={1} value={quantity} onChange={(e) => { setQuantity(e.target.valueAsNumber); setErrors({ ...errors, quantity: undefined }); }} error={errors.quantity} /></div><button type="button" onClick={() => { setProductUrl(SAMPLE_URL); setErrors({}); }} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-brand-soft px-4 py-2 text-sm font-semibold text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><Sparkles className="h-4 w-4" />Use sample product</button>{mutation.isError && <div className="mt-6"><ErrorPanel error={mutation.error} onRetry={() => mutation.reset()} /></div>}{mutation.isPending && <div aria-live="polite" className="mt-6 rounded-2xl bg-brand-soft p-4"><div className="mb-3 h-1.5 overflow-hidden rounded-full bg-brand/10"><div className="h-full rounded-full bg-brand transition-all" style={{ width: `${((stage + 1) / stages.length) * 100}%` }} /></div><p className="text-sm font-semibold text-brand">{stages[stage]}</p><p className="mt-1 text-xs text-muted">One secure request is in progress.</p></div>}<Button type="submit" loading={mutation.isPending} className="mt-7 w-full">{mutation.isPending ? stages[stage] : <>Create quotation <ArrowRight className="h-4 w-4" /></>}</Button></form>
      <aside className="space-y-4"><div className="rounded-3xl border border-black/[.07] bg-white p-5 shadow-soft"><PackageSearch className="h-5 w-5 text-brand" /><h2 className="mt-4 font-semibold">Current fee guide</h2>{rates.data ? <dl className="mt-4 grid gap-3 text-sm"><div className="flex justify-between"><dt className="text-muted">Service fee</dt><dd className="font-semibold">{rates.data.serviceFeePercent}%</dd></div><div className="flex justify-between"><dt className="text-muted">Base shipping</dt><dd className="font-semibold"><Money value={rates.data.estimatedShippingFeeVnd} /></dd></div><div className="flex justify-between"><dt className="text-muted">Deposit</dt><dd className="font-semibold">{rates.data.depositPercent}%</dd></div></dl> : <p className="mt-3 text-sm text-muted">Rates will be confirmed in your quotation.</p>}</div><div className="rounded-3xl bg-ink p-5 text-white"><p className="text-sm font-semibold">Transparent by design</p><p className="mt-2 text-sm leading-6 text-white/65">The backend calculates all financial values. This interface never replaces the authoritative quotation.</p></div></aside></div>
  </PageContainer></AppShell>;
}
