import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Box, Calendar, MapPin, Ruler, Scale } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { AppShell, PageContainer, PageHeader } from "../app/layouts/AppShell";
import { CopyButton } from "../components/ui/CopyButton";
import { ErrorPanel, PageSkeleton } from "../components/ui/Feedback";
import { StatusBadge } from "../components/ui/StatusBadge";
import { frontendApi } from "../features/api";
import { formatDateTime } from "../lib/format";
import { packageStatusPresentation } from "../lib/presentation";
export function PackageDetailPage() { const { packageId = "" } = useParams(); const query = useQuery({ queryKey: ["package", packageId], queryFn: () => frontendApi.getPackage(packageId) }); if (query.isPending) return <AppShell operations><PageContainer><PageSkeleton /></PageContainer></AppShell>; if (query.isError) return <AppShell operations><PageContainer narrow><ErrorPanel error={query.error} onRetry={() => void query.refetch()} /></PageContainer></AppShell>; const pkg = query.data; const status = packageStatusPresentation[pkg.status]; return <AppShell operations><PageContainer narrow><PageHeader eyebrow="Warehouse receipt" title="Package received." description="The warehouse record is complete. The order will advance through Kafka and the customer timeline will refresh from the source of truth." /><section className="overflow-hidden rounded-[2rem] bg-white shadow-card"><div className="flex flex-col justify-between gap-5 bg-ink p-6 text-white sm:flex-row sm:items-center sm:p-8"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><Box /></span><div><p className="text-xs uppercase tracking-wider text-white/50">Package ID</p><p className="mt-1 break-all font-mono text-sm">{pkg.packageId}</p></div></div><StatusBadge label={status.label} tone={status.tone} /></div><div className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><Detail icon={<MapPin />} label="Order ID" value={pkg.orderId} copy /><Detail icon={<Box />} label="Source tracking number" value={pkg.sourceTrackingNumber} copy /><Detail icon={<MapPin />} label="Warehouse code" value={pkg.warehouseCode} /><Detail icon={<Scale />} label="Weight" value={`${pkg.weightKg} kg`} /><Detail icon={<Ruler />} label="Dimensions" value={`${pkg.lengthCm} × ${pkg.widthCm} × ${pkg.heightCm} cm`} /><Detail icon={<Calendar />} label="Received" value={formatDateTime(pkg.receivedAt)} /></div><div className="flex flex-col gap-3 border-t border-black/[.07] p-6 sm:flex-row sm:p-8"><Link to={`/tracking/${pkg.orderId}`} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-ink px-5 text-sm font-semibold text-white">View customer tracking <ArrowRight className="h-4 w-4" /></Link><Link to="/warehouse/receive" className="inline-flex min-h-12 flex-1 items-center justify-center rounded-2xl border border-black/10 bg-white px-5 text-sm font-semibold">Receive another package</Link></div></section></PageContainer></AppShell>; }
function Detail({ icon, label, value, copy = false }: { icon: React.ReactNode; label: string; value: string; copy?: boolean }) { return <div className="flex gap-3 rounded-2xl bg-canvas p-4"><span className="mt-0.5 text-brand [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div className="min-w-0"><p className="text-xs text-muted">{label}</p><div className="mt-1 flex items-center gap-1"><p className="break-all text-sm font-semibold tabular-nums">{value}</p>{copy && <CopyButton value={value} />}</div></div></div>; }
