import { useQuery } from "@tanstack/react-query";
import { Coins, Globe2, PackageCheck } from "lucide-react";
import { AppShell, PageContainer, PageHeader } from "../app/layouts/AppShell";
import { ErrorPanel, PageSkeleton } from "../components/ui/Feedback";
import { Money } from "../components/ui/Money";
import { frontendApi } from "../features/api";
import { formatDateTime } from "../lib/format";
export function RatesPage({ admin = false }: { admin?: boolean }) { const query = useQuery({ queryKey: ["rates"], queryFn: frontendApi.getRates }); if (query.isPending) return <AppShell operations={admin}><PageContainer><PageSkeleton /></PageContainer></AppShell>; if (query.isError) return <AppShell operations={admin}><PageContainer narrow><ErrorPanel error={query.error} onRetry={() => void query.refetch()} /></PageContainer></AppShell>; const rates = query.data; return <AppShell operations={admin}><PageContainer><PageHeader eyebrow={admin ? "Read-only administration" : "Transparent pricing"} title={admin ? "System rate snapshot." : "Know the rates before you start."} description={admin ? "This operational view reflects the backend's current cached rate snapshot. Editing controls are intentionally unavailable." : "Current external reference rates guide quotation calculations. Every final value is returned by the backend in your quotation."} /><div className="grid gap-5 md:grid-cols-3"><RateCard icon={<Coins />} label="Service fee" value={`${rates.serviceFeePercent}%`} note="Applied to the converted product amount" /><RateCard icon={<PackageCheck />} label="Estimated base shipping" value={<Money value={rates.estimatedShippingFeeVnd} />} note="Included in the quotation estimate" /><RateCard icon={<Globe2 />} label="Deposit" value={`${rates.depositPercent}%`} note="Calculated when the order is created" /></div><section className="mt-8 rounded-[2rem] bg-white p-6 shadow-card sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-semibold">Exchange-rate table</h2><p className="mt-1 text-sm text-muted">Supported source currencies expressed in VND.</p></div><p className="text-xs text-subtle">Effective {formatDateTime(rates.effectiveAt)}</p></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[480px] border-collapse text-left text-sm"><thead><tr className="border-b border-black/10 text-xs uppercase tracking-wider text-muted"><th className="px-4 py-3">Currency</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Exchange rate</th></tr></thead><tbody>{rates.supportedCurrencies.map((currency) => <tr key={currency} className="border-b border-black/[.06] last:border-0"><td className="px-4 py-4 font-semibold">{currency}</td><td className="px-4 py-4"><span className="rounded-full bg-success-soft px-3 py-1 text-xs font-semibold text-success-dark">Supported</span></td><td className="px-4 py-4 text-right font-semibold tabular-nums">{rates.exchangeRates[currency].toLocaleString("en-US")} VND</td></tr>)}</tbody></table></div></section></PageContainer></AppShell>; }
function RateCard({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: React.ReactNode; note: string }) { return <article className="rounded-[2rem] bg-white p-6 shadow-soft"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-soft text-brand">{icon}</span><p className="mt-6 text-sm font-semibold text-muted">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{value}</p><p className="mt-3 text-xs leading-5 text-subtle">{note}</p></article>; }
